### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by fxrysh** [racz16/WebGL-GLSL-Editor#19]
Is there a way to configure this formatter to output the following:
```glsl
if (some) {
  doSomething();
}
```
Currently, it's output the following:
```glsl
if(some) {
  doSomething();
}
```
As you can see, there's no space between the keyword (`if`) and the bracket (`(...)`).

**Comment by racz16** [comment]
Currently you can't change this, but if I have some time, I'll add formatting options.

**Comment by fxrysh** [comment]
Maybe set this (`if (...)`) as the default option? It seems a lot cleaner.
