### ISSUE TITLE
how to disable Inlay hints for xxx.glsl files in vscode?

### ISSUE THREAD

**Issue by wzwxwc** [racz16/WebGL-GLSL-Editor#25]
how to disable Inlay hints for xxx.glsl files in vscode?

**Comment by racz16** [comment]
In `File / Preferences / Settings`, set `Editor > Inlay Hints: Enabled` to `off`. 
![image](https://user-images.githubusercontent.com/19560859/191835028-c2ea3d66-f327-4182-8fa8-9e0ebac6750d.png)

**Comment by wzwxwc** [comment]
@racz16 
It works,Thank you very much.
