### ISSUE TITLE
Color picker removes .0

### ISSUE THREAD

**Issue by nstringham** [racz16/WebGL-GLSL-Editor#26]
if you use the color picker to choose the color `#FF0000` it will change the value to be `vec4(1f, 0f, 0f, 1f)` but it should be `vec4(1.0f, 0.0f, 0.0f, 1.0f)`

**Comment by racz16** [comment]
Thanks for your feedback, you're right, it's not correct. In the next release, I'll fix this problem. Until then you can either fix it manually or use one of the earlier versions (like version 1.3.1) of the extension where the color picker didn't add the `f` suffix. And while `1f` is invalid, `1` is a valid `int`, which is converted into a `float` in the constructor.

**Comment by racz16** [comment]
Fixed the problem, it'll be part of the next release. Here is the commit: 5ef58ba7a36bae6911fece22268f9c83d3845b81. Feel free the give me feedback if my solution doesn't work well.
