### ISSUE TITLE
Emoji in the comments breaks formatter

### ISSUE THREAD

**Issue by MelonCode** [racz16/WebGL-GLSL-Editor#33]
Hi, first of all, thank you for great extension! 

I recently started to learn GLSL and copied one of the code samples from google, syntax highlighting worked great, however weirds thing happened on file format - words across the code were cut off randomly.
After some experiments I figured out that it's caused by an emoji character in the comments

https://user-images.githubusercontent.com/3682284/211686540-c0a9cd97-602e-4094-a2e7-9c7807bd7bc9.mp4

It's not a huge deal, but definitely looks like a bug

**Comment by racz16** [comment]
Hi, thank you, and sorry for the late answer. Fixed the problem, it'll be part of the next release. I wrote a comment into the code explaining why the deprecated class works. Here is the commit: 15d7bb5747d940488f02db5a0520c0561bfd414c. Feel free the give me feedback if my solution doesn't work well.
