### ISSUE TITLE
how can i ignore some type checking or add global typings?

### ISSUE THREAD

**Issue by lisiur** [racz16/WebGL-GLSL-Editor#4]
I'm using Threejs to build my app. Threejs will auto inject some attribute and uniform vars such as `attibute vec3 position`. When I comment the `position`, the extension complains, how to handle this situation?

**Comment by racz16** [comment]
The extension can't handle such injections. If you rename the file to .glsl extension, the compiler won't run, therefore you won't see any errors.

**Comment by lisiur** [comment]
Thanks for replying. I removed the redundant statement at runtime. Anyway it's a good extension,  thanks again.

**Comment by LeonardoRick** [comment]
Can you provide the code related to what you did @lisiur. By the way, what is the extension of your file so it shows compilation errors?

**Comment by WORMSS** [comment]
I just wanted to ask, is this STILL the official stance that it's not possible? 

I have to do 
```ts
// = object.matrixWorld
uniform mat4 modelMatrix;

// = camera.matrixWorldInverse * object.matrixWorld
uniform mat4 modelViewMatrix;

// = camera.projectionMatrix
uniform mat4 projectionMatrix;

// = camera.matrixWorldInverse
uniform mat4 viewMatrix;

// = inverse transpose of modelViewMatrix
uniform mat3 normalMatrix;

// = camera position in world space
uniform vec3 cameraPosition;

attribute vec3 position;
attribute vec3 normal;
attribute vec2 uv;

void main() {

  vec4 result;
  result = vec4(position, 1.0);

  gl_Position = projectionMatrix * modelViewMatrix * result;
}
```
To make it easy to work with
but having those in the file causes the code to no run.
So I then have to do 
```ts
// // = object.matrixWorld
// uniform mat4 modelMatrix;

// // = camera.matrixWorldInverse * object.matrixWorld
// uniform mat4 modelViewMatrix;

// // = camera.projectionMatrix
// uniform mat4 projectionMatrix;

// // = camera.matrixWorldInverse
// uniform mat4 viewMatrix;

// // = inverse transpose of modelViewMatrix
// uniform mat3 normalMatrix;

// // = camera position in world space
// uniform vec3 cameraPosition;

// attribute vec3 position;
// attribute vec3 normal;
// attribute vec2 uv;

void main() {

  vec4 result;
  result = vec4(position, 1.0);

  gl_Position = projectionMatrix * modelViewMatrix * result;
}
```
Which allows it to run, but results in 

![Image](https://github.com/user-attachments/assets/cddd5163-f349-4a58-bc67-4f354b07cde2)
