### ISSUE TITLE
formatter removes newline escapes

### ISSUE THREAD

**Issue by IiroUllin** [racz16/WebGL-GLSL-Editor#40]
e.g.

#define FUN fun(){\\
return 123.4\\
}

The first newline escape will be kept, however the second one will be removed (I put double escapes here to make '\\' symbols visible.)

**Comment by racz16** [comment]
I just fixed the problem with this commit: b81d3150b5f1114381fe5439576448bf0426b97e. However, as I explained in #39, this won't solve the real problem. The formatter will no longer delete the `\` character, but they won't work properly either. For example, if you write this:
```
str\
uct
```
it won't recognize the keyword `struct`. You can try the changes locally if you want, and it'll be part of the next release (which I'll publish in the coming days).

**Comment by IiroUllin** [comment]
Fantastic!
