### ISSUE TITLE
disable inlay hints

### ISSUE THREAD

**Issue by JirkaDellOro** [racz16/WebGL-GLSL-Editor#41]
Great extension!

Is it possible to disable the inlay hints? To me, it's more irritating than helpful.

**Comment by racz16** [comment]
Thanks! There are multiple ways to influence the behavior of inlay hints. First of all, you can either enable or disable inlay hints globally. But actually, there are two more options: only show inlay hints if you press `ctrl`+`alt` and only hide them if you press `ctrl`+`alt`. And, of course, you can do either of them only in your workspace (not globally). You can find this option in File / Preferences / Settings and search for inlay hints.
![image](https://github.com/racz16/WebGL-GLSL-Editor/assets/19560859/835c97cb-56c2-44ea-b8bb-e983e6c92e81)
