### ISSUE TITLE
Can't load textures with a relative path.

### ISSUE THREAD

**Issue by ducdat-ptit** [racz16/WebGL-GLSL-Editor#45]
Loading the textures directly in fragment works for me with a remote http path, but doesn't with a relative path. 

I can load an url  in code:
`uniform sampler2D u_texture_1; // https://rawgit.com/actarian/plausible-brdf-shader/master/textures/noise/cloud-1.png`
or in settings.json file:
`"glsl-canvas.textures": {
	"0": "https://rawgit.com/actarian/plausible-brdf-shader/master/textures/noise/cloud-1.png",
}`

But I can't load my images in the workspace. I've tried out several options and different vscode workspace hierarchies but no success.

**Comment by racz16** [comment]
I think you're not in the right place. This is not the repository of glsl-canvas. But it seems that [others have the same issue](https://github.com/actarian/vscode-glsl-canvas/issues/68).
