### ISSUE TITLE
Disabling auto formatting for a specific code region

### ISSUE THREAD

**Issue by evgenykochetkov** [racz16/WebGL-GLSL-Editor#48]
Hi! First of all, thanks for a very useful plugin!

Is it possible to disable auto formatting for a specific section? Similar to
```
/* eslint-disable */
...
/* eslint-enable */
```
or 
```
// clang-format off
...
// clang-format on
```

Sometimes custom indentation makes code much more readable, for example when defining matrices or writing some long calculation with a lot of similar operands.

**Comment by racz16** [comment]
Hi, thanks, I'm glad you like it. No, you can't really disable formatting for specific sections. However, there are 2 workarounds that might help you. First of all, the extension supports Format Selection, so if you select some code and either press `Ctrl` +`K` and then `Ctrl` + `F`, or right-click and select `Format Selection`, the formatter will only format the selected code. The other workaround is to use comments. My formatter doesn't really change spaces before and after comments and you can take advantage of it like this:
```
mat4 mat = mat4(1.0, 0.0, 0.0, 0.0,
/**/            0.0, 1.0, 0.0, 0.0,
/**/            0.0, 0.0, 1.0, 0.0,
/**/            0.0, 0.0, 0.0, 1.0);
```
Maybe not the most beautiful solutions, but I hope they help.

**Comment by evgenykochetkov** [comment]
The comments workaround works perfectly fine for my use cases, thank you!
