### ISSUE TITLE
How to Disable Inlay Hints in WebGL GLSL Editor

### ISSUE THREAD

**Issue by ZRNOF** [racz16/WebGL-GLSL-Editor#53]
Hello,

I have been using WebGL GLSL Editor and I'm finding the Inlay Hints feature to be a bit distracting. Can I modify it in settings.json to disable this feature?

Thank you in advance for your help!

Best regards,

Zaron Chen

**Comment by racz16** [comment]
Hi! Yes, for example, [here I explain how can you influence inlay hints](https://github.com/racz16/WebGL-GLSL-Editor/issues/41).

**Comment by ZRNOF** [comment]
Ok! Thank you so much!
