### ISSUE TITLE
[Feature]: Support a "default" #version in settings

### ISSUE THREAD

**Issue by robodrunk** [racz16/WebGL-GLSL-Editor#62]
### Feature details

It is common to omit #version directive in a shader source file due to provisioning of such lines at shader loading time.

Please add an option to specify a default version line when it's missing in the source.

Thank you for a great addon.

**Comment by racz16** [comment]
You can do this by enabling `Code injection` in the settings, and setting the `Code Injection Source` to the version directive, like `#version 300 es`.

**Comment by robodrunk** [comment]
Thank you, this worked!
