### ISSUE TITLE
How to disable the labels in function calls

### ISSUE THREAD

**Issue by thomas-worcay** [racz16/WebGL-GLSL-Editor#67]
### Content

Hello,

first of all thanks a lot for this great extension!
I have one question though and can't find a solution in the config of the plugin. When I call a function, I always see these labels:
<img width="346" alt="image" src="https://github.com/user-attachments/assets/d3e075ba-4516-4510-8151-d26f7f6eb91c">

Since they are not visible in any of the screenshots in the documentation, I assume that I can turn them off.
Unfortunately I can't figure out how.

Thanks a lot for your time and help!

Cheers,
Thomas

**Comment by racz16** [comment]
Hi! Thank you, I'm glad you found it useful. Yes, it is possible, for example, [here I explain how you can influence inlay hints](https://github.com/racz16/WebGL-GLSL-Editor/issues/41).

**Comment by thomas-worcay** [comment]
Ah thanks. I was searching for the keyword "label" and didn't find the existing issue because of that.
